version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  redis:
    image: redis:6.2
    command: redis-server --requirepass changeme --port 6379
    container_name: 'redis6.2-growth'
    hostname: redis6.2-growth
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379

networks:
  rabbitmq_go_net:
    driver: bridge