version: '3'

services:

  zookeeper:
    image: zookeeper
    container_name: 'zookeeper-growth'
    restart: always
    ports:
    - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: 'kafka-growth'
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: 'growth-chat:1:3' ## TOPIC:partition:replica count
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:6.2
    command: redis-server --requirepass changeme --port 6379
    container_name: 'redis6.2-growth'
    hostname: redis6.2-growth
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    restart: always
    container_name: 'mysql-growth'
    ports:
    - 13306:3306
    environment:
      - MYSQL_DATABASE=MYSQL
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/Shared/data/mysql:/var/lib/mysql



#  rabbitmq:
#    image: rabbitmq:3.8-management
#    container_name: 'rabbitmq'
#    ports:
#      - 5672:5672
#      - 15672:15672
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#    networks:
#      - rabbitmq_go_net
#networks:
#  rabbitmq_go_net:
#    driver: bridge