server:
  port: 30000

spring:
  cloud:
    gateway:
      routes:
        - id: CHAT_SERVICE
          uri: lb://CHAT_SERVICE
          predicates:
            - Path=/chat/**

        - id: MEMBER_SERVICE
          uri : lb://MEMBER_SERVICE
          predicates:
            - Path=/member/**
            - Path=/members/**

  application:
    name: API-GATEWAY
